export const cars = [
    {section: 1, brand: "Audi", carNumber: 'ВО2278ВІ', color: "darkgreen", type: "sedan",  fee: 3000, appNum: 2, carAmount: 1},
    {section: 1, brand: "Peugeot", carNumber: 'ВО9260ВО', color: "white", type: "hatchback",  fee: 3000, appNum: 7, carAmount: 1},
    {section: 1, brand: "", carNumber: 'ВО6937', color: "white", type: "",  fee: 3000, appNum: 14, carAmount: 1},
    {section: 1, brand: "Opel", carNumber: 'ВО4085АЕ', color: "violet", type: "hatchback",  fee: 3000, appNum: 15, carAmount: 1},
    {section: 2, brand: "Hyundai", carNumber: 'ВМ7101ВХ', color: "gray", type: "hatchback",  fee: 3000, appNum: 18, carAmount: 1},
    {section: 2, brand: "Nissan", carNumber: 'ВО9924НА', color: "red", type: "hatchback",  fee: 6000, appNum: 20, carAmount: 2},
    {section: 2, brand: "", carNumber: 'ВО7076НА', color: "", type: "hatchback",  fee: 0, appNum: 20, carAmount: 2, note: "інше"},
    {section: 2, brand: "Ford", carNumber: 'ВО9537ЕТ', color: "darkgrey", type: "hatchback",  fee: 3000, appNum: 22, carAmount: 1},
    {section: 2, brand: "Opel", carNumber: 'ВО5173СО', color: "white", type: "sedan",  fee: 3000, appNum: 27, carAmount: 1},
    {section: 2, brand: "Volkswagen", carNumber: 'ВО2315ЕР', color: "darkgrey", type: "hatchback",  fee: 3000, appNum: 29, carAmount: 1},
    {section: 3, brand: "Hyundai", carNumber: 'ВО8684СХ', color: "brown", type: "sedan",  fee: 3000, appNum: 32, carAmount: 1},
    {section: 3, brand: "Renault", carNumber: 'ВО6749ЕІ', color: "steelblue", type: "hatchback",  fee: 3000, appNum: 34, carAmount: 2},
    {section: 3, brand: "ВАЗ", carNumber: 'ВО0774АС', color: "red", type: "sedan",  fee: 0, appNum: 34, carAmount: 2, note: "інше"},
    {section: 3, brand: "Audi", carNumber: 'ВО2649ЕЕ', color: "black", type: "sedan",  fee: 3000, appNum: 37, carAmount: 1},
    {section: 3, brand: "", carNumber: 'ВС5198ТІ', color: "white", type: "",  fee: 3000, appNum: 38, carAmount: 1},
    {section: 3, brand: "Nissan", carNumber: 'ВО3454ЕВ', color: "black", type: "hatchback",  fee: 6000, appNum: 39, carAmount: 2},
    {section: 3, brand: "Honda", carNumber: 'ВО1381ВМ', color: "palevioletred", type: "hatchback",  fee: 0, appNum: 39, carAmount: 2, note: "2-е авто"},
    {section: 3, brand: "", carNumber: 'ВО3367АМ', color: "white", type: "",  fee: 3000, appNum: 42, carAmount: 1},
    {section: 4, brand: "Skoda", carNumber: 'ВО7380ЕМ', color: "black", type: "hatchback",  fee: 3000, appNum: 46, carAmount: 1},
    {section: 4, brand: "Ford", carNumber: 'КЕ4833АВ', color: "white", type: "hatchback",  fee: 1000, appNum: 47, carAmount: 1},
    {section: 4, brand: "Skoda", carNumber: 'АХ7496КА', color: "white", type: "sedan",  fee: 3000, appNum: 48, carAmount: 1},
    {section: 4, brand: "Hyundai", carNumber: 'ВО4059СР', color: "orange", type: "sedan",  fee: 3000, appNum: 49, carAmount: 1},
    {section: 4, brand: "", carNumber: 'ВО6256АН', color: "white", type: "hatchback",  fee: 3000, appNum: 51, carAmount: 1},
    {section: 4, brand: "Opel", carNumber: 'ВО0668СВ', color: "midnightBlue", type: "sedan",  fee: 3000, appNum: 52, carAmount: 1},
    {section: 4, brand: "Volkswagen", carNumber: 'ВО3139EI', color: "khaki", type: "hatchback",  fee: 3000, appNum: 56, carAmount: 1},
    {section: 4, brand: "ВАЗ", carNumber: 'ВО1760АІ', color: "paleTurquoise", type: "hatchback",  fee: 3000, appNum: 58, carAmount: 1},
    {section: 5, brand: "Hyundai", carNumber: 'ВО9542АІ', color: "navy", type: "sedan",  fee: 3000, appNum: 62, carAmount: 1},
    {section: 5, brand: "Opel", carNumber: 'ВО3774ВХ', color: "gold", type: "sedan",  fee: 3000, appNum: 63, carAmount: 1},
    {section: 5, brand: "Ford", carNumber: 'АМ1358КЕ', color: "white", type: "sedan",  fee: 3000, appNum: 64, carAmount: 1},
    {section: 5, brand: "", carNumber: 'СВ0370ЕО', color: "white", type: "",  fee: 3000, appNum: 66, carAmount: 1},
    {section: 5, brand: "Peugeot", carNumber: 'ВО6120ВО', color: "gray", type: "hatchback",  fee: 3000, appNum: 68, carAmount: 1},
    {section: 5, brand: "", carNumber: 'ВО8280АМ', color: "white", type: "",  fee: 3000, appNum: 70, carAmount: 2},
    {section: 5, brand: "Toyota", carNumber: 'ВО5894СМ', color: "black", type: "hatchback",  fee: 0, appNum: 70, carAmount: 2, note: "інше"},
    {section: 5, brand: "Honda", carNumber: 'ВО2727СЕ', color: "black", type: "hatchback",  fee: 3000, appNum: 72, carAmount: 1},
    {section: 6, brand: "", carNumber: 'ВО4597СК', color: "midnightBlue", type: "hatchback",  fee: 1000, appNum: 76, carAmount: 1, note: "гості"},
    {section: 6, brand: "Ford", carNumber: 'ВО9880АТ', color: "red", type: "hatchback",  fee: 3000, appNum: 83, carAmount: 1},
    {section: 6, brand: "Seat", carNumber: 'ВО3150ЕН', color: "black", type: "hatchback",  fee: 3000, appNum: 88, carAmount: 1},
    {section: 6, brand: "Volkswagen", carNumber: 'ВО4142ЕІ', color: "black", type: "hatchback",  fee: 6000, appNum: 89, carAmount: 2},
    {section: 6, brand: "Ford", carNumber: 'ВО0114ВК', color: "white", type: "sedan",  fee: 0, appNum: 89, carAmount: 2, note: "інше"},
    {section: 7, brand: "Mercedes", carNumber: 'ВО1028ЕХ', color: "midnightBlue", type: "hatchback",  fee: 3000, appNum: 93, carAmount: 2},
    {section: 7, brand: "Opel", carNumber: 'ВО6160СХ', color: "steelblue", type: "hatchback",  fee: 0, appNum: 93, carAmount: 2, note: "гості"},
    {section: 7, brand: "Peugeot", carNumber: 'ВО9396ЕК', color: "black", type: "hatchback",  fee: 3000, appNum: 96, carAmount: 1},
    {section: 7, brand: "Mitsubishi", carNumber: 'ВО9782EX', color: "black", type: "sedan",  fee: 3000, appNum: 97, carAmount: 1},
    {section: 7, brand: "Opel", carNumber: 'ВО6551СК', color: "steelBlue", type: "hatchback",  fee: 3000, appNum: 101, carAmount: 1},
    {section: 7, brand: "", carNumber: 'ВО1587СК', color: "gray", type: "sedan",  fee: 3000, appNum: 102, carAmount: 1},
    {section: 8, brand: "Peugeot", carNumber: 'ВО8814АН', color: "powderblue", type: "sedan",  fee: 3000, appNum: 107, carAmount: 1},
    {section: 8, brand: "Volkswagen", carNumber: 'ВО0501АВ', color: "navy", type: "sedan",  fee: 3000, appNum: 109, carAmount: 1},
    {section: 8, brand: "BMW", carNumber: 'ВО4837СК', color: "steelBlue", type: "sedan",  fee: 3000, appNum: 112, carAmount: 1},
    {section: 8, brand: "", carNumber: 'ВО0643ЕА', color: "white", type: "",  fee: 3000, appNum: 117, carAmount: 1},
    {section: null, brand: "Volkswagen", carNumber: 'ВО3507ЕТ', color: "gray", type: "hatchback",  fee: 0, appNum: null, carAmount: 1, note: "гості"},
    // {section: 8, brand: "Testing car", carNumber: 'ВО', color: "white", type: "",  fee: 3000, appNum: 150, carAmount: 1},
];

export const _authPassword = "osbb8"